# cloud-config
#
package_update: true
package_upgrade: true

timezone: 'Europe/Bratislava'

hostname: minio1

users:
  - default
  - name: tommy
    groups:
      - sudo
    sudo:
      - ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
                ssh_authorized_keys:
                        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOCp4ntj12jMLvF5j/Jx79/4TbEtkescbtXfIH3yvrDN
